import express from 'express';
import path from 'path';
import { GoogleGenAI } from "@google/genai";
import { createServer as createViteServer } from 'vite';

// Lazy loader for GoogleGenAI to prevent start-up crashes if key is initially empty
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY environment variable is required to access the AI Monetization Advisor. Please register your key in Settings > Secrets.");
    }
    aiClient = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClient;
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Route: Health Check
  app.get('/api/health', (req, res) => {
    res.json({
      status: 'active',
      timestamp: new Date().toISOString(),
      service: 'Nexora Monetize full-stack application'
    });
  });

  // API Route: AI Monetization Advisor (Protected server-side proxy)
  app.post('/api/gemini/advisor', async (req, res) => {
    try {
      const { prompt, chatHistory, customContext } = req.body;
      const client = getGeminiClient();

      if (!prompt) {
        res.status(400).json({ error: "Prompt parameter is required." });
        return;
      }

      const systemPrompt = `You are Nexora Monetize AI, the ultimate expert on passive-income streams, SaaS, content channels, and digital monetization models.
Your target is to assist users in building structured income strategies for channels like YouTube, TikTok, Google Play Apps, Music Streaming, film, Blogging, and high-ticket Freelancing.
Be metrics-driven, crisp, practical, and direct. Use rich text formatting, bullet lists, markdown tables of expected metrics, and steps for first monetization.
Always align suggestions with their monthly income targets and chosen resources. Keep responses highly encouraging yet rigorously realistic.

Context:
${customContext ? JSON.stringify(customContext) : 'Default monetization query.'}`;

      // Reconstruct content history for google/genai SDK format
      const formattedContents: any[] = [];
      if (chatHistory && Array.isArray(chatHistory)) {
        chatHistory.forEach((msg: any) => {
          formattedContents.push({
            role: msg.role === 'model' ? 'model' : 'user',
            parts: [{ text: msg.text }]
          });
        });
      }

      // Push latest user prompt
      formattedContents.push({
        role: 'user',
        parts: [{ text: prompt }]
      });

      const response = await client.models.generateContent({
        model: "gemini-3.5-flash",
        contents: formattedContents,
        config: {
          systemInstruction: systemPrompt,
          temperature: 0.7,
        },
      });

      res.json({
        text: response.text || "No response generated by Nexora AI.",
        modelUsed: "gemini-3.5-flash"
      });
    } catch (err: any) {
      console.error("Error in AI Monetization Advisor API:", err);
      res.status(500).json({
        error: err.message || "An exception occurred while generating advice. Ensure your GEMINI_API_KEY is configured in the workspace settings."
      });
    }
  });

  // API Route: Payments simulated checkout session (Stripe integration ready)
  app.post('/api/stripe/create-checkout-session', (req, res) => {
    try {
      const { planId, email } = req.body;
      if (!planId) {
        res.status(400).json({ error: "planId parameter is required." });
        return;
      }

      const sessionToken = `session_mock_stripe_${Math.random().toString(36).substring(2, 10)}`;
      
      // Simulate redirection to Stripe payment processor page
      // It points directly back to our simulated checkout success handler
      const checkoutUrl = `/checkout-success?plan=${planId}&session_id=${sessionToken}&email=${encodeURIComponent(email || 'user@nexora.com')}`;

      res.json({
        sessionId: sessionToken,
        url: checkoutUrl
      });
    } catch (err: any) {
      res.status(500).json({ error: err.message || "Failed to create checkout session." });
    }
  });

  // Vite Integration: Handle Asset Serving & hot reload fallback
  if (process.env.NODE_ENV !== "production") {
    console.log("Starting server in development mode with Vite middleware...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    console.log("Starting server in production mode with static direct serving...");
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Nexora Monetize is running on host 0.0.0.0, port ${PORT}`);
  });
}

startServer().catch((error) => {
  console.error("Fatal exception during server boot:", error);
});
